source "https://rubygems.org"

ruby "2.3.1"

gem "cuba",         "~> 3.8.0"
gem "jwt",          "~> 1.5.4"
gem "oj",           "~> 2.17.5"
gem "pg",           "~> 0.19.0"
gem "rack-parser",  "~> 0.7.0"
gem "sequel",       "~> 4.40.0"
gem "shield",       "~> 2.1.0"
gem "shotgun",      "~> 0.9.2", require: false

group :test do
  gem "database_cleaner", "~> 1.5.0"
  gem "rack-test",        "~> 0.6.3"
  gem "rspec",            "~> 3.5.0"
  gem "faker",            "~> 1.6.6"
end
